version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      actions-dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*"
